(function(){
  var LABELS = {cologne:'Cologne',jackets:'Jackets',clothing:'Clothing',accessories:'Accessories'};
  var SIZE_PRESETS = {
    fragrance:[{label:'30ml',mult:0.72},{label:'50ml',mult:1},{label:'100ml',mult:1.62}],
    apparel:[{label:'S',mult:0.96},{label:'M',mult:1},{label:'L',mult:1},{label:'XL',mult:1.04},{label:'XXL',mult:1.08}],
    jacket:[{label:'S',mult:0.94},{label:'M',mult:1},{label:'L',mult:1},{label:'XL',mult:1.06}],
    gloves:[{label:'S',mult:1},{label:'M',mult:1},{label:'L',mult:1},{label:'XL',mult:1.04}],
    bracelet:[{label:'M',mult:1},{label:'L',mult:1.05}],
    one:[{label:'One Size',mult:1}]
  };
  var META = {
    cologne:{selectorLabel:'Blend',options:['Original','Dark Chrome','Iron Wood','Midnight Amber'],sizeLabel:'Bottle Size',sizeSet:'fragrance',guideHref:'care-guide.html',guideText:'Scent guide',stockPill:'🚚 Free Shipping on $75+',bars:[74,16,6,3,1]},
    jackets:{selectorLabel:'Finish',options:['Blackout','Graphite','Burnt Tan'],sizeLabel:'Fit',sizeSet:'jacket',guideHref:'size-guide.html',guideText:'Size guide',stockPill:'🛡️ Built for daily wear',bars:[68,21,7,3,1]},
    clothing:{selectorLabel:'Colorway',options:['Blackout','Bone White','Road Grey'],sizeLabel:'Fit',sizeSet:'apparel',guideHref:'size-guide.html',guideText:'Size guide',stockPill:'↩️ 30-Day Returns',bars:[71,18,7,3,1]},
    accessories:{selectorLabel:'Colorway',options:['Blackout','Chrome','Olive'],sizeLabel:'Size',sizeSet:'one',guideHref:'care-guide.html',guideText:'Care guide',stockPill:'⚡ Fast dispatch in 24h',bars:[70,19,7,3,1]}
  };
  function round(n){ return Math.round(n * 100) / 100; }
  function makeVariants(base, preset){
    return preset.map(function(item){ return {label:item.label, price:round(base * item.mult), soldOut:!!item.soldOut}; });
  }
  function product(data){
    var meta = META[data.category];
    var preset = SIZE_PRESETS[data.sizeSet || meta.sizeSet];
    data.options = data.options || meta.options;
    data.sizeLabel = data.sizeLabel || meta.sizeLabel;
    data.selectorLabel = data.selectorLabel || meta.selectorLabel;
    data.guideHref = data.guideHref || meta.guideHref;
    data.guideText = data.guideText || meta.guideText;
    data.sizes = makeVariants(data.price, preset);
    data.categoryLabel = LABELS[data.category];
    data.bars = data.bars || meta.bars;
    data.qaCount = data.qaCount || Math.max(28, Math.round(data.reviews * 0.22));
    data.stockPill = data.stockPill || meta.stockPill;
    return data;
  }
  var products = [
    product({id:1,category:'cologne',sub:'EDT · Signature',name:'Phantom Rider EDT',price:67,originalPrice:89,rating:4.9,reviews:892,sales:1240,badgeClass:'badge-sale',badgeLabel:'25% OFF',emoji:'💎',gradient:'linear-gradient(135deg,#1A1A2E,#2E1A1A)',descriptor:'Smoky citrus, black pepper, and worn-leather depth.',material:'Frosted glass flacon with zinc-alloy cap.',fit:'N/A',care:'Store away from direct heat and spray onto pulse points or jacket lining.',performance:'8–12 hour wear with a warm smoky dry-down.',season:'Fall / Winter / Cool spring',madeIn:'Grasse, France',year:'2025',stock:23,tags:[['Top Notes','🍋','Bergamot & Black Pepper'],['Heart','🌿','Vetiver & Tobacco Leaf'],['Base','🪵','Cedarwood, Musk & Leather']]}),
    product({id:2,category:'cologne',sub:'EDP · Night Drive',name:'Iron Highway EDP',price:125,rating:4.7,reviews:641,sales:820,emoji:'🌙',gradient:'linear-gradient(135deg,#12121E,#1E1412)',descriptor:'Cardamom, black tea, resin, and suede warmth.',material:'Smoked-glass eau de parfum bottle.',fit:'N/A',care:'One or two sprays is enough for most wearers.',performance:'10–14 hour wear with a denser projection.',season:'Fall / Winter',madeIn:'Grasse, France',year:'2025',stock:17,tags:[['Opening','🫖','Cardamom & Black Tea'],['Heart','🔥','Charred Cedar & Incense'],['Base','🧥','Amber Resin & Suede']]}),
    product({id:3,category:'cologne',sub:'EDT · Fresh Chrome',name:'Chrome Dusk EDT',price:63,originalPrice:79,rating:4.9,reviews:1204,sales:2100,badgeClass:'badge-hot',badgeLabel:'Best Seller',emoji:'⚙️',gradient:'linear-gradient(135deg,#0E0E1A,#1A1A2A)',descriptor:'Bright grapefruit, neroli, and a cool cedar finish.',material:'Brushed chrome presentation bottle.',fit:'N/A',care:'Spray on fresh skin or tee collars for a lighter trail.',performance:'6–8 hour wear built for daytime use.',season:'Spring / Summer / Everyday',madeIn:'Grasse, France',year:'2025',stock:31,tags:[['Opening','🍊','Grapefruit & Neroli'],['Heart','⚙️','Mineral Cedar & Sage'],['Base','☁️','White Musk & Amber']]}),
    product({id:4,category:'cologne',sub:'Extrait · Limited',name:'Road Warrior Extrait',price:145,rating:4.7,reviews:389,sales:540,badgeClass:'badge-ltd',badgeLabel:'Limited',emoji:'🔥',gradient:'linear-gradient(135deg,#180C0C,#2A1010)',descriptor:'Saffron, resinous woods, smoked vanilla, and leather.',material:'Collector-grade extrait bottle with heavy cap.',fit:'N/A',care:'Apply lightly; the extrait wears close and long.',performance:'12+ hour wear with dense evening presence.',season:'Fall / Winter / Night',madeIn:'Grasse, France',year:'2025',stock:8,tags:[['Opening','🧡','Saffron & Bitter Orange'],['Heart','🪵','Labdanum & Resin'],['Base','🔥','Leather & Smoked Vanilla']]}),
    product({id:5,category:'cologne',sub:'EDP · New Release',name:'Midnight Chrome EDP',price:110,rating:4.9,reviews:528,sales:780,badgeClass:'badge-new',badgeLabel:'New',emoji:'🌃',gradient:'linear-gradient(135deg,#1A1E2A,#0A1A2A)',descriptor:'Bergamot peel, incense, and soft cashmere woods.',material:'Gloss-black bottle with chrome ring cap.',fit:'N/A',care:'Spray on neck and forearms for an even dry-down.',performance:'9–12 hour wear with smooth moderate projection.',season:'Year-round evenings',madeIn:'Grasse, France',year:'2026',stock:14,tags:[['Opening','🌙','Bergamot Peel'],['Heart','⛓️','Incense & Violet Leaf'],['Base','🪞','Cashmere Woods & Amber']]}),
    product({id:6,category:'cologne',sub:'EDT · Asphalt Blend',name:'Asphalt & Smoke EDT',price:68,originalPrice:85,rating:4.6,reviews:274,sales:490,badgeClass:'badge-sale',badgeLabel:'20% OFF',emoji:'🏍️',gradient:'linear-gradient(135deg,#200A00,#2A1500)',descriptor:'Dry amber, cedar smoke, and charred citrus.',material:'Matte charcoal EDT bottle.',fit:'N/A',care:'Best on warm skin and the inside of jackets.',performance:'7–9 hour wear with a dry road-worn finish.',season:'Year-round casual wear',madeIn:'Grasse, France',year:'2025',stock:19,tags:[['Opening','🍊','Citrus Rind & Pink Pepper'],['Heart','🌫️','Cedar Smoke & Sage'],['Base','🛣️','Dry Amber & Musk']]}),
    product({id:7,category:'cologne',sub:'EDP · Explorer',name:'Canyon Petrol EDP',price:118,rating:4.8,reviews:342,sales:415,badgeClass:'badge-new',badgeLabel:'Desert Drop',emoji:'⛽',gradient:'linear-gradient(135deg,#102133,#0E1822)',descriptor:'Juniper, mineral rain, soft leather, and moss.',material:'Petrol-blue eau de parfum bottle.',fit:'N/A',care:'Ideal on neck and collarbone for a mineral opening.',performance:'8–10 hour wear with crisp freshness.',season:'Spring / Fall / Travel',madeIn:'Grasse, France',year:'2026',stock:12,tags:[['Opening','🌧️','Juniper & Mineral Rain'],['Heart','⛽','Iris & Petrol Accord'],['Base','🧥','Suede Leather & Moss']]}),
    product({id:8,category:'cologne',sub:'Parfum Oil · Travel',name:'Atlas Leather Elixir',price:54,rating:4.8,reviews:211,sales:298,badgeClass:'badge-new',badgeLabel:'Travel',emoji:'🧴',gradient:'linear-gradient(135deg,#2B1C10,#19110B)',descriptor:'Cardamom, cocoa husk, and creamy suede.',material:'Alcohol-free roll-on parfum oil vial.',fit:'N/A',care:'Apply to wrists and inner elbows; reapply lightly as desired.',performance:'7–9 hour close-to-skin wear.',season:'Year-round travel',madeIn:'Lyon, France',year:'2026',stock:27,sizeSet:'one',sizeLabel:'Bottle Size',options:['Atlas Leather','Cocoa Suede','Night Cardamom'],guideText:'Fragrance guide',tags:[['Opening','🌰','Cardamom & Cocoa Husk'],['Heart','🧴','Soft Iris & Tonka'],['Base','🧥','Suede & Benzoin']]}),

    product({id:9,category:'jackets',sub:'Leather Rider',name:'Moto Chrome Rider Jacket',price:228,originalPrice:285,rating:4.9,reviews:412,sales:680,badgeClass:'badge-sale',badgeLabel:'20% OFF',emoji:'🧥',gradient:'linear-gradient(135deg,#1E1A0E,#2A1A0A)',descriptor:'Full-grain leather, clean paneling, and chrome hardware.',material:'1.2mm full-grain leather with satin lining.',fit:'Regular-to-tailored fit with a clean shoulder line.',care:'Condition twice a season and hang on a wide hanger.',performance:'Strong wind resistance and premium structure.',season:'Fall / Winter / Cool spring',madeIn:'Istanbul, Türkiye',year:'2025',stock:16,tags:[['Shell','🪡','Full-Grain Leather'],['Function','🛡️','Reinforced Panels'],['Detail','✨','Chrome Hardware']]}),
    product({id:10,category:'jackets',sub:'Leather Touring',name:'Iron Asphalt Full-Grain Jacket',price:320,rating:4.7,reviews:188,sales:290,emoji:'🛞',gradient:'linear-gradient(135deg,#1A1410,#2A1A0E)',descriptor:'Waxed touring leather, storm flap, and quilted liner.',material:'1.3mm waxed leather with removable liner.',fit:'Regular fit with room for thermals and hoodies.',care:'Spot clean the shell and remove the liner before storage.',performance:'Excellent weather coverage for colder commutes.',season:'Fall / Winter',madeIn:'Istanbul, Türkiye',year:'2025',stock:9,tags:[['Shell','🧱','Waxed Leather'],['Coverage','🌬️','Storm Collar & Placket'],['Comfort','🧵','Quilted Liner']]}),
    product({id:11,category:'jackets',sub:'Leather Classic',name:'Speed Classic Leather Jacket',price:199,originalPrice:265,rating:4.9,reviews:573,sales:1020,badgeClass:'badge-sale',badgeLabel:'25% OFF',emoji:'🏁',gradient:'linear-gradient(135deg,#1A0E14,#200A18)',descriptor:'A lean café-racer cut in supple lamb leather.',material:'Supple lamb leather with breathable lining.',fit:'Streamlined fit that layers easily over tees and hoodies.',care:'Use light conditioner sparingly and avoid overstuffing pockets.',performance:'Lightweight enough for daily city wear.',season:'Spring / Fall / Year-round layering',madeIn:'Izmir, Türkiye',year:'2026',stock:22,tags:[['Shell','🧥','Supple Lamb Leather'],['Fit','📐','Café-Racer Shape'],['Use','🔁','Daily Wear Ready']]}),
    product({id:12,category:'jackets',sub:'Textile Riding',name:'Road King Riding Jacket',price:299,rating:4.7,reviews:231,sales:360,badgeClass:'badge-new',badgeLabel:'New',emoji:'🏍️',gradient:'linear-gradient(135deg,#1A1210,#2A1A14)',descriptor:'Mixed textile-and-leather shell with airflow panels.',material:'Abrasion-resistant textile body with leather trim.',fit:'Athletic fit with articulated sleeves.',care:'Wipe clean, air dry after wet rides, and keep vents lint-free.',performance:'Most breathable jacket in the line.',season:'Spring / Summer / Early fall',madeIn:'Porto, Portugal',year:'2026',stock:13,tags:[['Shell','🧵','Mixed Materials'],['Venting','💨','Airflow Panels'],['Cut','⚡','Articulated Fit']]}),
    product({id:13,category:'jackets',sub:'Waxed Canvas',name:'Canyon Storm Waxed Jacket',price:189,rating:4.8,reviews:267,sales:398,badgeClass:'badge-hot',badgeLabel:'Editor Pick',emoji:'🌧️',gradient:'linear-gradient(135deg,#27311E,#151C10)',descriptor:'Dry-wax canvas, cord collar, and workwear utility.',material:'Dry-wax canvas shell with brushed cotton lining.',fit:'Relaxed fit for layering over fleece and tees.',care:'Spot clean the shell and re-wax lightly after heavy use.',performance:'Weather-ready transitional outer layer.',season:'Spring / Fall',madeIn:'Porto, Portugal',year:'2026',stock:18,tags:[['Shell','🌧️','Dry-Wax Canvas'],['Detail','🪵','Cord Collar'],['Mood','🧳','Utility Layer']]}),
    product({id:14,category:'jackets',sub:'Mesh Overshirt',name:'Trackside Mesh Overshirt',price:154,rating:4.8,reviews:194,sales:284,badgeClass:'badge-new',badgeLabel:'Warm Weather',emoji:'💨',gradient:'linear-gradient(135deg,#111827,#1F2937)',descriptor:'Performance mesh, hidden snaps, and reflective trim.',material:'Durable mesh shell with tonal snap front.',fit:'Relaxed overshirt fit with straight hem.',care:'Machine wash cold on delicate and hang dry.',performance:'Fast-drying and highly breathable.',season:'Spring / Summer',madeIn:'Porto, Portugal',year:'2026',stock:25,tags:[['Fabric','🌬️','Performance Mesh'],['Trim','✨','Reflective Piping'],['Ease','🎒','Packable Weight']]}),

    product({id:15,category:'clothing',sub:'T-Shirt',name:'Phantom Graphic Tee',price:36,originalPrice:45,rating:4.9,reviews:1102,sales:2800,badgeClass:'badge-hot',badgeLabel:'Hot',emoji:'👕',gradient:'linear-gradient(135deg,#1A1A1A,#0E1620)',descriptor:'Heavyweight cotton, washed finish, and oversized back art.',material:'280gsm ring-spun cotton jersey.',fit:'Relaxed fit with a straight body and slightly dropped shoulder.',care:'Machine wash cold inside out and tumble low or line dry.',performance:'Keeps its shape while softening over time.',season:'Year-round',madeIn:'Braga, Portugal',year:'2025',stock:41,tags:[['Fabric','🧵','280gsm Heavy Cotton'],['Fit','📏','Relaxed Block'],['Graphic','🎨','Oversized Back Print']]}),
    product({id:16,category:'clothing',sub:'T-Shirt',name:'Speed Lines Print Tee',price:42,rating:4.7,reviews:445,sales:920,emoji:'🏁',gradient:'linear-gradient(135deg,#1A1A14,#14180A)',descriptor:'Heavy cotton tee with tonal racing stripe artwork.',material:'240gsm cotton jersey with soft hand feel.',fit:'Regular fit with a neat shoulder and easy torso.',care:'Wash cold and avoid ironing directly on the print.',performance:'Breathable enough for everyday wear.',season:'Year-round',madeIn:'Braga, Portugal',year:'2025',stock:36,tags:[['Fabric','🧶','Heavy Cotton Jersey'],['Graphic','🏁','Racing Stripe Print'],['Styling','🪞','Versatile Shape']]}),
    product({id:17,category:'clothing',sub:'T-Shirt',name:'Throttle Chrome Tee',price:48,rating:4.9,reviews:789,sales:1650,badgeClass:'badge-hot',badgeLabel:'Hot',emoji:'✨',gradient:'linear-gradient(135deg,#1A1A0A,#2A200A)',descriptor:'Boxy fit, chrome chest hit, and brushed cotton surface.',material:'260gsm combed cotton with soft brushed finish.',fit:'Boxy fit with extra room in the sleeve and body.',care:'Wash cold and lay flat or tumble low.',performance:'Holds a strong silhouette without feeling stiff.',season:'Year-round',madeIn:'Braga, Portugal',year:'2025',stock:29,tags:[['Fabric','🧵','Combed Cotton'],['Fit','◼️','Boxy Shape'],['Detail','✨','Chrome Chest Hit']]}),
    product({id:18,category:'clothing',sub:'T-Shirt',name:'Chrome Rider Tee',price:35,originalPrice:44,rating:4.6,reviews:334,sales:740,badgeClass:'badge-sale',badgeLabel:'20% OFF',emoji:'🪙',gradient:'linear-gradient(135deg,#100A1A,#200A1A)',descriptor:'Garment-dyed cotton with vintage racing mood.',material:'220gsm garment-dyed cotton jersey.',fit:'Classic fit with a slightly shorter body.',care:'Wash separately the first two times to protect the dye.',performance:'Softens quickly and ages with character.',season:'Year-round',madeIn:'Braga, Portugal',year:'2025',stock:33,tags:[['Fabric','🎨','Garment-Dyed Cotton'],['Mood','🕰️','Vintage Racing Graphic'],['Wear','🤝','Easy Everyday Use']]}),
    product({id:19,category:'clothing',sub:'Hoodie',name:'Iron Moto Pullover Hoodie',price:68,originalPrice:85,rating:4.9,reviews:623,sales:1100,badgeClass:'badge-sale',badgeLabel:'20% OFF',emoji:'🧥',gradient:'linear-gradient(135deg,#1A1A14,#14180A)',descriptor:'Dense fleece, tonal puff print, and a structured hood.',material:'420gsm brushed-back cotton fleece.',fit:'Regular fit with a roomy hood and clean body.',care:'Machine wash cold and air dry or tumble low.',performance:'Warm and substantial for cold-weather layering.',season:'Fall / Winter / Cool spring',madeIn:'Braga, Portugal',year:'2025',stock:27,tags:[['Fabric','🧶','420gsm Fleece'],['Structure','🧱','Reinforced Hood'],['Style','🔲','Tonal Puff Print']]}),
    product({id:20,category:'clothing',sub:'Zip Hoodie',name:'Midnight Cruiser Zip Hoodie',price:95,rating:4.7,reviews:291,sales:460,badgeClass:'badge-new',badgeLabel:'New',emoji:'🌃',gradient:'linear-gradient(135deg,#141420,#1E1430)',descriptor:'Smooth-face fleece, double zip, and a hidden sleeve pocket.',material:'380gsm smooth-face fleece with double-zip closure.',fit:'Regular fit with a slightly tapered waist.',care:'Close the zips before washing and tumble low or hang dry.',performance:'Warm enough for travel and city layering.',season:'Fall / Winter / Travel',madeIn:'Braga, Portugal',year:'2026',stock:18,tags:[['Fabric','🧵','Smooth-Face Fleece'],['Function','↕️','Double Zip'],['Detail','📎','Hidden Sleeve Pocket']]}),
    product({id:21,category:'clothing',sub:'Bottoms',name:'Rider Cargo Pants',price:76,originalPrice:95,rating:4.9,reviews:347,sales:680,badgeClass:'badge-sale',badgeLabel:'20% OFF',emoji:'🎽',gradient:'linear-gradient(135deg,#101020,#200E30)',descriptor:'Straight cargo fit with articulated knee and utility pockets.',material:'Midweight cotton-nylon twill with mechanical stretch.',fit:'Straight fit with room through the thigh and a clean hem.',care:'Machine wash cold, hang dry, and warm iron if needed.',performance:'Durable enough for commuting and long days.',season:'Year-round',madeIn:'Braga, Portugal',year:'2025',stock:26,tags:[['Fabric','🪡','Cotton-Nylon Twill'],['Function','🦿','Articulated Knee'],['Storage','📦','Low-Profile Utility']]}),
    product({id:22,category:'clothing',sub:'Bottoms',name:'Speed Racer Joggers',price:75,rating:4.6,reviews:198,sales:380,emoji:'⚡',gradient:'linear-gradient(135deg,#141020,#1E0A2A)',descriptor:'Technical double-knit jogger with zip cuffs and a tapered leg.',material:'Technical double-knit jersey with stretch waistband.',fit:'Tapered fit with a clean seat and narrow ankle.',care:'Wash cold and avoid high heat to protect the zip trim.',performance:'Travel-friendly and crease resistant.',season:'Year-round',madeIn:'Braga, Portugal',year:'2025',stock:22,tags:[['Fabric','🧵','Technical Double-Knit'],['Shape','📉','Tapered Leg'],['Function','🔓','Zip Cuffs']]}),
    product({id:23,category:'clothing',sub:'Bottoms',name:'Chrome Track Shorts',price:44,originalPrice:55,rating:4.9,reviews:412,sales:820,badgeClass:'badge-sale',badgeLabel:'20% OFF',emoji:'🩳',gradient:'linear-gradient(135deg,#0E0E20,#1A1428)',descriptor:'Technical summer short with contrast side tape and zip storage.',material:'Technical shell with mesh pocket bags.',fit:'Regular fit with a slightly tailored leg opening.',care:'Machine wash cold and line dry for best finish retention.',performance:'Lightweight, breathable, and quick to dry.',season:'Spring / Summer',madeIn:'Braga, Portugal',year:'2026',stock:31,tags:[['Fabric','🌤️','Technical Shell'],['Storage','🔒','Zip Pockets'],['Style','🏁','Contrast Tape']]}),
    product({id:24,category:'clothing',sub:'Long Sleeve',name:'Iron Cross Long Sleeve Tee',price:38,rating:4.8,reviews:288,sales:490,badgeClass:'badge-new',badgeLabel:'New',emoji:'🦾',gradient:'linear-gradient(135deg,#101018,#1A1020)',descriptor:'Heavy long sleeve with sleeve graphics and washed feel.',material:'260gsm cotton jersey with ribbed cuffs.',fit:'Relaxed fit with a straight body and long sleeves.',care:'Machine wash cold inside out to protect the sleeve prints.',performance:'Strong transitional layer with a premium drape.',season:'Spring / Fall / Layering',madeIn:'Braga, Portugal',year:'2026',stock:24,tags:[['Fabric','🧶','Heavy Jersey'],['Detail','🦾','Sleeve Graphics'],['Use','🍂','Transitional Layer']]}),
    product({id:25,category:'clothing',sub:'Knit',name:'Workshop Waffle Henley',price:58,rating:4.8,reviews:156,sales:240,badgeClass:'badge-new',badgeLabel:'Quiet Luxury',emoji:'🧰',gradient:'linear-gradient(135deg,#2A2415,#15120A)',descriptor:'Textured waffle knit with metal snaps and workwear energy.',material:'Cotton-poly waffle knit with reinforced placket.',fit:'Regular fit with room in the chest and sleeves.',care:'Wash cold on gentle and reshape while damp.',performance:'Breathable base layer that traps warmth.',season:'Fall / Winter / Layering',madeIn:'Braga, Portugal',year:'2026',stock:19,tags:[['Fabric','🧇','Waffle Knit'],['Trim','🔩','Metal Snaps'],['Layering','🧥','Base-Layer Hero']]}),
    product({id:26,category:'clothing',sub:'Overshirt',name:'Signal Flannel Overshirt',price:88,rating:4.7,reviews:141,sales:208,badgeClass:'badge-new',badgeLabel:'Layering',emoji:'🪵',gradient:'linear-gradient(135deg,#2A1C16,#16100D)',descriptor:'Heavy brushed flannel with tonal checks and utility pockets.',material:'Heavy brushed cotton flannel with yarn-dyed check.',fit:'Relaxed overshirt fit for easy layering.',care:'Machine wash cold and line dry to keep the brushed face clean.',performance:'Warm, soft, and easy to throw over basics.',season:'Fall / Winter',madeIn:'Braga, Portugal',year:'2026',stock:17,tags:[['Fabric','🌲','Brushed Flannel'],['Pattern','🟫','Tonal Check'],['Layering','📚','Overshirt Shape']]}),
    product({id:27,category:'clothing',sub:'Denim',name:'Apex Selvedge Jeans',price:112,rating:4.8,reviews:173,sales:256,badgeClass:'badge-new',badgeLabel:'Premium Denim',emoji:'👖',gradient:'linear-gradient(135deg,#0F172A,#1E293B)',descriptor:'Straight-taper selvedge denim with reflective cuff detail.',material:'13oz selvedge denim with matte black hardware.',fit:'Straight-taper fit with room at the thigh and a neat ankle.',care:'Wash sparingly inside out and hang dry.',performance:'Breaks in beautifully while keeping its shape.',season:'Year-round',madeIn:'Porto, Portugal',year:'2026',stock:21,tags:[['Fabric','👖','13oz Selvedge Denim'],['Fit','📏','Straight-Taper'],['Detail','🌙','Reflective Cuff']]}),
    product({id:28,category:'clothing',sub:'Shirt',name:'Paddock Camp Shirt',price:64,rating:4.7,reviews:128,sales:196,badgeClass:'badge-new',badgeLabel:'Summer Drop',emoji:'🗺️',gradient:'linear-gradient(135deg,#164E63,#0F172A)',descriptor:'Relaxed camp shirt with a subtle race-map print.',material:'Lightweight viscose blend with recycled buttons.',fit:'Relaxed fit with open collar and straight hem.',care:'Cold wash on gentle cycle and hang dry.',performance:'Lightweight and breathable in warm weather.',season:'Spring / Summer',madeIn:'Braga, Portugal',year:'2026',stock:23,tags:[['Fabric','🌤️','Viscose Blend'],['Print','🗺️','Race-Map Pattern'],['Shape','🌊','Open Collar']]}),

    product({id:29,category:'accessories',sub:'Hat',name:'Chrome Moto Snapback Cap',price:35,rating:4.9,reviews:1245,sales:3100,badgeClass:'badge-hot',badgeLabel:'Best Seller',emoji:'🧢',gradient:'linear-gradient(135deg,#1A1E1A,#0E1A0E)',descriptor:'Structured snapback with raised chrome embroidery.',material:'Structured cotton twill with snapback closure.',fit:'Adjustable fit for most head sizes.',care:'Spot clean and avoid machine washing to preserve the crown.',performance:'Keeps its structure well and travels easily.',season:'Year-round',madeIn:'Porto, Portugal',year:'2025',stock:52,tags:[['Build','🧢','Structured Crown'],['Detail','✨','Raised Embroidery'],['Ease','🔁','Adjustable Snapback']]}),
    product({id:30,category:'accessories',sub:'Gloves',name:'Iron Rider Riding Gloves',price:44,originalPrice:55,rating:4.6,reviews:388,sales:690,badgeClass:'badge-sale',badgeLabel:'20% OFF',emoji:'🧤',gradient:'linear-gradient(135deg,#1A1A0A,#2A200A)',descriptor:'Touchscreen-ready glove with perforated palm and low-profile padding.',material:'Goat leather palm with stretch back panel.',fit:'True-to-size glove fit with flexible articulation.',care:'Wipe clean after use and air dry naturally.',performance:'Reliable grip and dexterity for everyday riding.',season:'Year-round',madeIn:'Porto, Portugal',year:'2025',stock:18,sizeSet:'gloves',tags:[['Palm','🖐️','Perforated Leather'],['Function','📱','Touchscreen Tips'],['Protection','🛡️','Low-Profile Padding']]}),
    product({id:31,category:'accessories',sub:'Beanie',name:'Speed Rider Beanie',price:28,rating:4.9,reviews:567,sales:1340,emoji:'🧶',gradient:'linear-gradient(135deg,#141414,#1E1414)',descriptor:'Soft rib beanie with tonal patch and clean fold.',material:'Acrylic-wool blend rib knit.',fit:'Stretch fit suitable for most head sizes.',care:'Hand wash or wool cycle, then lay flat to dry.',performance:'Warm, soft, and easy to pack.',season:'Fall / Winter',madeIn:'Porto, Portugal',year:'2025',stock:34,tags:[['Knit','🧶','Soft Rib Blend'],['Branding','🏷️','Tonal Patch'],['Use','❄️','Winter Ready']]}),
    product({id:32,category:'accessories',sub:'Jewelry',name:'Throttle Chain Bracelet',price:22,rating:4.6,reviews:892,sales:2200,badgeClass:'badge-hot',badgeLabel:'Hot',emoji:'⛓️',gradient:'linear-gradient(135deg,#0A1A0A,#1A2A0A)',descriptor:'Brushed steel bracelet inspired by chain-link geometry.',material:'Brushed stainless steel with secure clasp.',fit:'Available in medium and large wrist sizes.',care:'Polish with a microfiber cloth and store in the pouch.',performance:'Resists daily wear and keeps a clean finish.',season:'Year-round',madeIn:'Milan, Italy',year:'2025',stock:38,sizeSet:'bracelet',tags:[['Material','⛓️','Brushed Steel'],['Shape','⚙️','Chain-Link Geometry'],['Wear','🤝','Stack or Solo']]}),
    product({id:33,category:'accessories',sub:'Bag',name:'Rider Canvas Tote Bag',price:36,originalPrice:45,rating:4.9,reviews:234,sales:510,badgeClass:'badge-sale',badgeLabel:'20% OFF',emoji:'👜',gradient:'linear-gradient(135deg,#0A0A1A,#1A0A1A)',descriptor:'Heavy canvas tote with webbing handles and a chrome snap.',material:'Heavyweight cotton canvas with structured webbing straps.',fit:'One-size vertical tote with roomy interior.',care:'Spot clean or hand wash, then air dry flat.',performance:'Strong enough for daily essentials and laptops.',season:'Year-round',madeIn:'Porto, Portugal',year:'2025',stock:25,tags:[['Fabric','👜','Heavy Canvas'],['Carry','🖐️','Webbing Handles'],['Utility','📚','Roomy Interior']]}),
    product({id:34,category:'accessories',sub:'Jewelry',name:'Moto Dog Tag Necklace',price:18,rating:4.9,reviews:1087,sales:2900,emoji:'🏅',gradient:'linear-gradient(135deg,#1A1A1A,#2A2A1A)',descriptor:'Minimal matte necklace with engraved route coordinates.',material:'Matte stainless steel tag with slim curb chain.',fit:'Adjustable chain length with a low-profile clasp.',care:'Wipe clean after wear and store flat in the pouch.',performance:'Comfortable for everyday wear under or over tees.',season:'Year-round',madeIn:'Milan, Italy',year:'2025',stock:44,tags:[['Material','🏅','Matte Steel'],['Story','🧭','Engraved Coordinates'],['Layering','📿','Slim Chain']]}),
    product({id:35,category:'accessories',sub:'Eyewear',name:'Rider Polarized Sunglasses',price:52,originalPrice:65,rating:4.6,reviews:189,sales:320,badgeClass:'badge-sale',badgeLabel:'20% OFF',emoji:'🕶️',gradient:'linear-gradient(135deg,#141A14,#1A2414)',descriptor:'Angular polarized frames with smoke lenses and metal-core temples.',material:'TR90 frame with polarized smoke lens.',fit:'Medium universal fit with flexible temple grip.',care:'Keep in the hard case and clean with the microfiber cloth.',performance:'Cuts glare well and stays comfortable on long days.',season:'Spring / Summer / Travel',madeIn:'Milan, Italy',year:'2026',stock:20,tags:[['Lens','🕶️','Polarized Smoke Lens'],['Frame','📐','Angular Shape'],['Storage','🧳','Hard Case Included']]}),
    product({id:36,category:'accessories',sub:'Bag',name:'Paddock Sling Bag',price:64,rating:4.8,reviews:165,sales:244,badgeClass:'badge-new',badgeLabel:'Carry Gear',emoji:'🎒',gradient:'linear-gradient(135deg,#111827,#0F172A)',descriptor:'Compact ballistic-nylon sling with hidden back pocket and utility loops.',material:'Ballistic nylon shell with ripstop lining.',fit:'Compact one-size sling with modular strap.',care:'Wipe clean with a damp cloth and air dry before storage.',performance:'Lightweight, weather resistant, and ideal for everyday carry.',season:'Year-round / Travel',madeIn:'Porto, Portugal',year:'2026',stock:28,tags:[['Shell','🎒','Ballistic Nylon'],['Access','🔒','Hidden Back Pocket'],['Carry','↔️','Modular Strap']]} )
  ];

  function getProduct(id){ id = parseInt(id,10); return products.find(function(item){ return item.id === id; }) || products[0]; }
  function getRelatedProducts(product, count){
    return products.filter(function(item){ return item.id !== product.id; }).sort(function(a,b){
      var catScore = (a.category === product.category ? 1 : 0) - (b.category === product.category ? 1 : 0);
      if (catScore !== 0) return -catScore;
      return b.sales - a.sales;
    }).slice(0, count || 4);
  }
  function getCategoryCounts(){ return products.reduce(function(acc,item){ acc.all++; acc[item.category]++; return acc; }, {all:0,cologne:0,jackets:0,clothing:0,accessories:0}); }
  function formatPrice(value){ return '$' + Number(value).toFixed(0); }
  function stars(rating){ var rounded = Math.round(rating); return '★★★★★'.slice(0, rounded) + '☆☆☆☆☆'.slice(0, 5-rounded); }
  function getWishlist(){ try { return JSON.parse(localStorage.getItem('twWishlist') || '[]'); } catch (e) { return []; } }
  function saveWishlist(ids){ localStorage.setItem('twWishlist', JSON.stringify(ids)); }
  function isWishlisted(id){ return getWishlist().indexOf(id) !== -1; }
  function toggleWishlist(id){ var ids = getWishlist(); var i = ids.indexOf(id); if (i === -1) ids.push(id); else ids.splice(i,1); saveWishlist(ids); return ids.indexOf(id) !== -1; }
  function escapeHtml(str){ return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'); }
  function buildCard(product, opts){
    opts = opts || {};
    var sale = product.originalPrice ? '<span class="price-original">' + formatPrice(product.originalPrice) + '</span><span class="price-save">Save ' + formatPrice(product.originalPrice - product.price) + '</span>' : '';
    var badge = product.badgeLabel ? '<span class="product-badge ' + product.badgeClass + '">' + product.badgeLabel + '</span>' : '';
    var wish = isWishlisted(product.id);
    return '<div class="product-card reveal" data-id="' + product.id + '" data-cat="' + product.category + '" data-price="' + product.price + '" data-rating="' + product.rating + '" data-reviews="' + product.reviews + '" data-new="' + (product.badgeClass === 'badge-new' ? 1 : 0) + '" data-sales="' + product.sales + '" onclick="window.location.href=\'product.html?id=' + product.id + '\'">'
      + '<div class="product-img" style="background:' + product.gradient + ';">' + product.emoji + badge
      + '<button class="product-wishlist' + (wish ? ' active' : '') + '" aria-label="Save ' + escapeHtml(product.name) + '" onclick="event.stopPropagation();toggleWishlistItem(' + product.id + ', this)">' + (wish ? '♥' : '♡') + '</button>'
      + '<div class="img-ph-label">Curated studio mockup</div>'
      + (opts.hideQuickAdd ? '' : '<button class="product-quick-add" onclick="event.stopPropagation();quickAdd(' + product.id + ',\'' + escapeHtml(product.name) + '\',' + product.price + ',\'' + product.category + '\')">+ Add to Cart</button>')
      + '</div><div class="product-info"><div class="product-category">' + product.categoryLabel + ' — ' + product.sub + '</div><div class="product-name">' + escapeHtml(product.name) + '</div><div class="product-rating"><span class="stars">' + stars(product.rating) + '</span><span class="rating-count">(' + product.reviews.toLocaleString() + ')</span></div><div class="product-price"><span class="price-current">' + formatPrice(product.price) + '</span>' + sale + '</div></div></div>';
  }
  window.TWCatalog = {products:products,meta:META,getProduct:getProduct,getRelatedProducts:getRelatedProducts,getCategoryCounts:getCategoryCounts,formatPrice:formatPrice,stars:stars,getWishlist:getWishlist,saveWishlist:saveWishlist,isWishlisted:isWishlisted,toggleWishlist:toggleWishlist,buildCard:buildCard,escapeHtml:escapeHtml};
})();
